#ifndef __CONFIG__
#define __CONFIG__

#define CONFIG_DEBUG 1
#define CONFIG_MCODE_EXPRESSION_MAX_ARGUMENTS 4
#define CONFIG_CODE_LINE_MAX_LENGTH 256
#define CONFIG_COMMENT_MAX_LENGTH 72
#define CONFIG_EXTEND_MIN_SIZE 32

#endif
